# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
#   schedule:
#     - cron: '0 0 * * 1'  # Run weekly on Mondays

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-html

      - name: Run tests
        run: |
          pytest --html=report.html --self-contained-html

      - name: Upload pytest report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: pytest-report
          path: report.html

      - name: Run tests in order
        run: |
          pytest tests/test_weather_api_with_city_ids.py
          pytest tests/test_temperatura_data_consistency.py --html=report.html --self-contained-html
