on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 1'  # Run weekly on Mondays

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        instance: [1, 2, 3, 4]
      fail-fast: false

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest pytest-xdist pytest-html

    - name: Run tests in parallel
      run: |
        python -m pytest -n auto --dist=loadfile --html=report-${{ matrix.instance }}.html --self-contained-html

    - name: Upload pytest report
      uses: ./.github/actions/upload-artifact
      with:
        name: pytest-report-${{ matrix.instance }}
        path: report-${{ matrix.instance }}.html
